### PR TITLE
[#175899260 ] Project skeleton to support  IO Payment Portal

### PR DESCRIPTION
**Pull request by infantesimone**
### Description 

The goal of this PR is to create an initial skeleton for the _IO Payment Portal_, consisting of two components:
- _io-pay-portal-fe_:  application frontend (not yet implemented); 
- _io-functions-pay-portal_: application backend.

### io-functions-pay-portal

The backend of the application is implemented as a Azure Function App, consisting of three functions:
- _ActivatePayment_:  invoked by http trigger on _api/v1/payment-activations_;
- _GetActivationStatus_: invoked by http trigger on _api/v1/payment-activations/{codiceContestoPagamento}_;
- _GetPaymentInfo_: invoked by http trigger on _/api/v1/payment-requests/{rptId}_.

The business logic of the functions is not implemented because it is out of scope of the PR.

### CODE REVIEW

**Comment by GiovanniMancini** [comment]
@infantesimone @pasqualespica  We may have left a useless folder for mocking durable functions' methods in the project root folder. I think it's just dead code. What about removing it?

**Comment by infantesimone** [comment]
It's correct 👍

**Comment by pasqualespica** [comment]
LGTM; I only proposed to modify the `index.yaml` with the missing definition, and in the REAMDE the shortcut`yarn docker` present in the `package.json`

**Comment by GiovanniMancini** [comment]
@infantesimone @pasqualespica When `yarn test` is used to run the test suite, only 1 test passes (the `Info` one). I think we should commit only tested code, to have always a 100% coverage. What do you think about such policy?

**Comment by infantesimone** [comment]
Ok, even if it is a template it is better to start with some (base) correct tests 👍

**Comment by GiovanniMancini** [comment]
I think it would be better if we align the node versions in docker files, `.nvmrc`, and `.node-version.` Wouldn't it?

**Comment by GiovanniMancini** [comment]
Thanks @infantesimone now test suite is syntactically correct. I think we should remove docker files for azurite and cosmosdb as they are not referenced in docker-compose. Or do you think we should leave them in the repo for future reference?

**Comment by infantesimone** [comment]
I don't know if these functions will connect to CosmosDB, so let's delete for now

**Pull request merged**
